env:
    APP_ENV: dev
    APP_NAME: gitops-platform
    HTTP_PORT: "8080"
    PG_DB: gitops_platform
    PG_HOST: host.docker.internal
    PG_PASSWORD: gitops123
    PG_PORT: "5432"
    PG_SSLMODE: disable
    PG_USER: gitops
    REDIS_ADDR: host.docker.internal:6379
    REDIS_DB: "0"
    REDIS_PASSWORD: ""
image:
    pullPolicy: IfNotPresent
    repository: gitops-platform/backend
    tag: dada
replicaCount: 1
service:
    port: 8080
    type: ClusterIP
